server:
  port: 8083
  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: InspectorManagement
  freemarker:
    suffix: .ftl
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/inspector?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: "newPassword1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
